version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - watchtower-data:/data/db

volumes:
  watchtower-data:
